apps/advisor/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import feeds as fd
from . import views as v

urlpatterns = [
    url(r'^$', v.PostListView.as_view(), name='posts-latest'),
    url(r'^feed/$', fd.LatestEntriesFeed(), name='posts-latest-feed'),
    url(r'^(?P<year>\d{4})/$', v.PostArchiveView.as_view(), name='posts-archive'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', v.PostArchiveView.as_view(), name='posts-archive'),
    url(r'^author/(?P<username>[\w\.@+-]+)/$', v.AuthorEntriesView.as_view(), name='posts-author'),
    url(r'^category/(?P<category>[\w\.@+-]+)/$', v.CategoryEntriesView.as_view(), name='posts-category'),
    url(r'^tag/(?P<tag>[-\w]+)/$', v.TaggedListView.as_view(), name='posts-tagged'),
    url(r'^tag/(?P<tag>[-\w]+)/feed/$', fd.TagFeed(), name='posts-tagged-feed'),
    url(r'^search$', v.SearchListView.as_view(), name='posts-search'),
    url(r'^(?P<path>.+)$', v.PostDetailView.as_view(), name='post-detail'),
]

apps/catalog/urls.py
# coding=utf-8
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt
from . import views as v


urlpatterns = [
    url(r'^search/contact$', v.SaveSimpleUserContactView.as_view(), name='simple_contact'),
    url(r'^search$', v.SearchByFormView.as_view(), name='search'),
    url(r'^bestatter/(?P<char>\w)$', v.SearchByCharView.as_view(), name='search_char'),
    url(r'^xhr/(?P<action>\w+)$', csrf_exempt(v.XhrView.as_view()), name='xhr'),
    url(r'^(?P<slug>[\w\-]+)-(?P<uid>[0-9a-f]{32})/contact$', v.FirmContactView.as_view(), name='firm_contact'),
    url(r'^(?P<slug>[\w\-]+)-(?P<uid>[0-9a-f]{32})$', v.DetailView.as_view(), name='detail'),
    url(r'^$', v.IndexView.as_view(), name='index'),
]

funeral_finder_cms/urls.py
# coding=utf-8
from __future__ import print_function
from cms.sitemaps import CMSSitemap
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib.admin import site as admin_site
from django.contrib.auth import urls as auth_urls
from django.contrib.auth import logout
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.views.static import serve
from django.views.decorators.csrf import csrf_exempt
from .views import XhrView, account_activate
from catalog.views import ProfileFirmsView, FirmEditView
# admin.autodiscover()


def dummy(r):
    pass


# urlpatterns = i18n_patterns(
urlpatterns = [
    url(r'^admin/', include(admin_site.urls)),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^xhr/(?P<action>\w+)$', csrf_exempt(XhrView.as_view()), name='xhr'),
    url(r'^catalog/', include('catalog.urls', namespace='catalog', app_name='catalog')),
    # url(r'^auth/logout-when-redirect'),
    url(r'^auth/', include(auth_urls, namespace='auth')),
    url(r'^accounts/profile-firms$', ProfileFirmsView.as_view(), name='profile_firms'),
    url(r'^accounts/profile-firms/(?P<pk>\d+)$', FirmEditView.as_view(), name='firm_edit'),
    url(r'^accounts/registration/(?P<who>\w+)', dummy, name='registration'),
    url(r'^accounts/activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})$',
        account_activate, name='account_activate'),
    # url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    # url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
# )

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += [
        url(r'^media(?P<path>.*)$', serve,
            kwargs={'document_root': settings.MEDIA_ROOT,
                    'show_indexes': True}),
    ] + staticfiles_urlpatterns()
    try:
        import debug_toolbar
    except ImportError:
        pass
    else:
        urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]

urlpatterns += [
    url(r'^(?P<path>.+(\.ico|\.png|\.gif|\.jpg|\.jpeg|\.txt))$', serve,
        kwargs={'document_root': settings.PUB_ROOT}, name='public'),
    url(r'^', include('cms.urls')),
]

templates/.include/article_text_trunc.html
<h1>{% if trunc_title %}{{ article.title|truncatechars:trunc_title }}{% else %}{{ article.title }}{% endif %}</h1>
<p class="text">{% if article.text %}{{ article.text.body|striptags|truncatechars:trunc_text }}{% endif %}</p>
<p class="read-more"><a href="{{ article.url }}" class="btn-link">Erfahren Sie mehr</a></p>

templates/.include/footer_links.html
<div class="columns">{% spaceless %}
    {% load i18n cms_tags %}{% url 'catalog:search' as srch_url %}
    <div class="search-by-city">
        <ul>
            <li><a href="{{ srch_url }}?query=Berlin">Bestattung in Berlin</a></li>
            <li><a href="{{ srch_url }}?query=Hamburg">Bestattung in Hamburg</a></li>
            <li><a href="{{ srch_url }}?query=M%C3%BCnchen">Bestattung in München</a></li>
        </ul>
    </div>
    <div class="search-by-city">
        <ul>
            <li><a href="{{ srch_url }}?query=K%C3%B6ln">Bestattung in Köln</a></li>
            <li><a href="{{ srch_url }}?query=Frankfurt%20am%20Main">Bestattung in Frankfurt</a></li>
            <li><a href="{{ srch_url }}?query=Stuttgart">Bestattung in Stuttgart</a></li>
        </ul>
    </div>
    <div class="search-by-city">
        <ul>
            <li><a href="{{ srch_url }}?query=D%C3%BCsseldorf">Bestattung in Düsseldorf</a></li>
            <li><a href="{{ srch_url }}?query=Dortmund">Bestattung in Dortmund</a></li>
            <li><a href="{{ srch_url }}?query=Essen">Bestattung in Essen</a></li>
        </ul>
    </div>
    <nav class="footer-menu">{% static_placeholder 'other_links' or %}
        <ul>
            <li><a href="#">AGB & Datenschutz</a></li>
            <li><a href="#">Impressum</a></li>
            <li><a href="#">Kontakt & Service</a></li>
        </ul>
    {% endstatic_placeholder %}</nav>
{% endspaceless %}</div>

<div class="search-by-char">{% spaceless %}
    <span>{% trans 'All funeral' %}:</span>
    {% for letter in FIRMS_ALPHABET %}
        <a{% if char != letter %} href="{% url 'catalog:search_char' char=letter %}"{% else %} class="curr"{% endif %}>{{ letter }}</a>
    {% endfor %}
{% endspaceless %}</div>

templates/.include/general_head_scripts.html
{% spaceless %}
    {% load sekizai_tags staticfiles %}

    {% addtoblock 'head_js' %}
        <!--[if lt IE 9]><script src="{% static 'js/IE9.min.js' %}"></script><script src="{% static 'js/respond.min.js' %}"></script><![endif]-->
    {% endaddtoblock %}

    {% addtoblock 'head_js' %}
        <script>{% include 'catalog/.include/settings.js' %}</script>
    {% endaddtoblock %}

    {% addtoblock 'head_js' %}
        <script src="{% static 'js/modernizr.js' %}"></script>
    {% endaddtoblock %}

    {% addtoblock 'head_js' %}
        <script src="{% static 'js/load_polyfills.js' %}"></script>
    {% endaddtoblock %}
{% endspaceless %}

templates/.include/html_head_ie.html
{% spaceless %}
    {% load staticfiles %}
    <!--[if lt IE 9]>
        <script src="{% static 'js/IE9.min.js' %}"></script>
        <script src="{% static 'js/respond.min.js' %}"></script>
    <![endif]-->
{% endspaceless %}

templates/.include/main_image.html
{% spaceless %}
{% load thumbnail %}
{% thumbnail picture.image dimensions crop=picture.crop upscale=picture.upscale as thumb %}
<figure class="visual"><img src="{{ thumb.url }}" alt="{{ picture.alt_text }}" width="{{ thumb.width }}" height="{{ thumb.height }}"/></figure>
{% endspaceless %}

templates/.include/menu_item.html
{% spaceless %}{% load cms_tags %}
<li>
    <a{% if page.reverse_id == p_id %} class="curr"{% endif %} href="{% page_url p_id %}">{% page_attribute 'menu_title' p_id %}</a>
</li>
{% endspaceless %}

templates/.include/overlay.html
{% load staticfiles widget_tweaks %}
<div class="overlay">
    <div class="win" id="modal-win"></div>
</div>
<script>document.createElement('modal');</script>
{% if contact_form %}<modal id="contact">{% spaceless %}
    <button id="close-win" class="close"><span class="svg"><img src="{% static 'img/times.svg' %}"/></span></button>
    <form class="send-msg" action="{% url 'catalog:xhr' action='query_contact' %}" method="post" name="simple_contact">
        {% csrf_token %}
        {% for hidden in contact_form.hidden_fields %}{{ hidden }}{% endfor %}
        <h2>Bitte geben sie ihre e-mail adresse an.</h2>
        <p class="help">Er hörte leise Schritte hinter sich. Das bedeutete nichts Gutes.</p>
        {% for fld in contact_form.visible_fields %}{% spaceless %}
            {% include 'catalog/.include/input_block.html' with field=fld label_class='sr-only' %}
        {% endspaceless %}{% endfor %}
        <div class="input-block">
            <button class="btn" type="submit" disabled>Abschicken</button>
        </div>
    </form>
{% endspaceless %}</modal>{% endif %}
{% if login_form %}<modal id="login">{% spaceless %}
    <button id="close-win" class="close"><span class="svg"><img src="{% static 'img/times.svg' %}"/></span></button>
    <form class="sign-in" action="{% url 'auth:login' %}" method="post">
        <h2>Bitte geben Sie Ihre Login Daten<br/> ein oder registrieren sie sich</h2>
        <div class="help"></div>
        {% csrf_token %}
        {% for hidden in login_form.hidden_fields %}{{ hidden }}{% endfor %}
        {% for fld in login_form.visible_fields %}{% spaceless %}
            {% include 'catalog/.include/input_block.html' with field=fld label_class='sr-only' %}
        {% endspaceless %}{% endfor %}
        <div class="inp-row justify">
            <button class="btn remind" type="submit" data-pass_remind="1">Registrieren / Passwort<br/>per Mail zuschicken</button>
            <button class="btn" type="submit" data-pass_remind="0">Einloggen</button>
        </div>
    </form>
{% endspaceless %}</modal>{% endif %}

templates/.include/search_form.html
        <form action="{% url 'catalog:search' %}" method="get" name="search">{% spaceless %}
            {% load widget_tweaks form_utils %}
            <div class="input-group">
                {% render_label form.query class='sr-only' %}
                {% render_field form.query class+='inp-str' placeholder=form.query.label autofocus='' %}
                <span class="input-group-btn">
                    <button type="submit" class="btn"><span>Suchen</span></button>
                </span>
            </div>
        {% endspaceless %}</form>