apps/advisor/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import feeds as fd
from . import views as v

urlpatterns = [
    url(r'^$', v.PostListView.as_view(), name='posts-latest'),
    url(r'^feed/$', fd.LatestEntriesFeed(), name='posts-latest-feed'),
    url(r'^(?P<year>\d{4})/$', v.PostArchiveView.as_view(), name='posts-archive'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', v.PostArchiveView.as_view(), name='posts-archive'),
    url(r'^author/(?P<username>[\w\.@+-]+)/$', v.AuthorEntriesView.as_view(), name='posts-author'),
    url(r'^category/(?P<category>[\w\.@+-]+)/$', v.CategoryEntriesView.as_view(), name='posts-category'),
    url(r'^tag/(?P<tag>[-\w]+)/$', v.TaggedListView.as_view(), name='posts-tagged'),
    url(r'^tag/(?P<tag>[-\w]+)/feed/$', fd.TagFeed(), name='posts-tagged-feed'),
    url(r'^search$', v.SearchListView.as_view(), name='posts-search'),
    url(r'^(?P<path>.+)$', v.PostDetailView.as_view(), name='post-detail'),
]

funeral_finder_cms/urls.py
# coding=utf-8
from __future__ import print_function
from cms.sitemaps import CMSSitemap
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib.admin import site as admin_site
from django.contrib.auth import urls as auth_urls
from django.contrib.auth import logout
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.views.static import serve
from django.views.decorators.csrf import csrf_exempt
from .views import XhrView, account_activate
from catalog.views import ProfileFirmsView, FirmEditView
# admin.autodiscover()


def dummy(r):
    pass


# urlpatterns = i18n_patterns(
urlpatterns = [
    url(r'^admin/', include(admin_site.urls)),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^xhr/(?P<action>\w+)$', csrf_exempt(XhrView.as_view()), name='xhr'),
    url(r'^catalog/', include('catalog.urls', namespace='catalog', app_name='catalog')),
    # url(r'^auth/logout-when-redirect'),
    url(r'^auth/', include(auth_urls, namespace='auth')),
    url(r'^accounts/profile-firms$', ProfileFirmsView.as_view(), name='profile_firms'),
    url(r'^accounts/profile-firms/(?P<pk>\d+)$', FirmEditView.as_view(), name='firm_edit'),
    url(r'^accounts/registration/(?P<who>\w+)', dummy, name='registration'),
    url(r'^accounts/activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})$',
        account_activate, name='account_activate'),
    # url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    # url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
# )

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += [
        url(r'^media(?P<path>.*)$', serve,
            kwargs={'document_root': settings.MEDIA_ROOT,
                    'show_indexes': True}),
    ] + staticfiles_urlpatterns()
    try:
        import debug_toolbar
    except ImportError:
        pass
    else:
        urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]

urlpatterns += [
    url(r'^(?P<path>.+(\.ico|\.png|\.gif|\.jpg|\.jpeg|\.txt))$', serve,
        kwargs={'document_root': settings.PUB_ROOT}, name='public'),
    url(r'^', include('cms.urls')),
]

apps/advisor/models.py
# coding=utf-8
from cms.models import CMSPlugin, PlaceholderField
from django.conf import settings as dj_settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone
from django.utils.encoding import force_text, python_2_unicode_compatible
from django.utils.html import escape, strip_tags
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import get_language
from djangocms_text_ckeditor.fields import HTMLField
# from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from filer.fields.image import FilerImageField
from meta_mixin.models import ModelMeta
from parler.managers import TranslationManager
from parler.models import TranslatableModel, TranslatedFields
from taggit_autosuggest.managers import TaggableManager

from .managers import GenericDateTaggedManager
from .settings import get_setting

ADVISOR_CURRENT_POST_IDENTIFIER = 'djangocms_post_current'


@python_2_unicode_compatible
class AdvisorCategory(TranslatableModel):
    """
    Blog category
    """
    parent = models.ForeignKey('self', verbose_name=_('parent'), null=True,
                               blank=True)
    date_created = models.DateTimeField(_('created at'), auto_now_add=True)
    date_modified = models.DateTimeField(_('modified at'), auto_now=True)

    translations = TranslatedFields(
        name=models.CharField(_('name'), max_length=255),
        slug=models.SlugField(_('slug'), blank=True, db_index=True),
        meta={'unique_together': (('language_code', 'slug'),)}
    )

    objects = TranslationManager()

    class Meta:
        verbose_name = _('adviser category')
        verbose_name_plural = _('adviser categories')

    @property
    def count(self):
        return self.blog_posts.filter(publish=True).count()

    @property
    def menu_level(self):
        if not hasattr(self, '_level'):
            self._level = 5
            if self.parent is None:
                self._level = 2
            elif self.parent.parent is None:
                self._level = 3
            elif self.parent.parent.parent is None:
                self._level = 4
        return self._level

    def get_absolute_url(self):
        lang = get_language()
        if self.has_translation(lang):
            slug = self.safe_translation_getter('slug', language_code=lang)
            return reverse('advisor:posts-category', kwargs={'category': slug})
        # in case category doesn't exist in this language, gracefully fallback
        # to posts-latest
        return reverse('advisor:posts-latest')

    def __str__(self):
        return self.safe_translation_getter('name')

    def save(self, *args, **kwargs):
        super(AdvisorCategory, self).save(*args, **kwargs)
        for lang in self.get_available_languages():
            self.set_current_language(lang)
            if not self.slug and self.name:
                self.slug = slugify(force_text(self.name))
        self.save_translations()


@python_2_unicode_compatible
class Post(ModelMeta, TranslatableModel):
    """
    Blog post
    """
    author = models.ForeignKey(dj_settings.AUTH_USER_MODEL,
                               verbose_name=_(u'author'), null=True, blank=True,
                               related_name='advisor_post_author')

    date_created = models.DateTimeField(_(u'created'), auto_now_add=True)
    date_modified = models.DateTimeField(_(u'last modified'), auto_now=True)
    date_published = models.DateTimeField(_(u'published Since'),
                                          default=timezone.now)
    date_published_end = models.DateTimeField(_(u'published Until'), null=True,
                                              blank=True)
    publish = models.BooleanField(_(u'publish'), default=False)
    categories = models.ManyToManyField('advisor.AdvisorCategory', verbose_name=_(u'category'),
                                        related_name='advisor_posts',)
    main_image = FilerImageField(verbose_name=_(u'main image'), blank=True, null=True,
                                 on_delete=models.SET_NULL,
                                 related_name='advisor_post_image')
    main_image_thumbnail = models.ForeignKey('cmsplugin_filer_image.ThumbnailOption',
                                             verbose_name=_(u'main image thumbnail'),
                                             related_name='advisor_post_thumbnail',
                                             on_delete=models.SET_NULL,
                                             blank=True, null=True)
    main_image_full = models.ForeignKey('cmsplugin_filer_image.ThumbnailOption',
                                        verbose_name=_(u'main image full'),
                                        related_name='advisor_post_full',
                                        on_delete=models.SET_NULL,
                                        blank=True, null=True)
    enable_comments = models.BooleanField(verbose_name=_(u'enable comments on post'),
                                          default=get_setting('ENABLE_COMMENTS'))
    sites = models.ManyToManyField('sites.Site', verbose_name=_(u'Site(s)'),
                                   related_name='advisor_posts', blank=True,
                                   help_text=_(u'Select sites in which to show the post. '
                                               u'If none is set it will be '
                                               u'visible in all the configured sites.'))

    translations = TranslatedFields(
        title=models.CharField(_(u'title'), max_length=255),
        slug=models.SlugField(_(u'slug'), blank=True, db_index=True),
        abstract=HTMLField(_(u'abstract'), blank=True, default=''),
        meta_description=models.TextField(verbose_name=_(u'post meta description'),
                                          blank=True, default=''),
        meta_keywords=models.TextField(verbose_name=_(u'post meta keywords'),
                                       blank=True, default=''),
        meta_title=models.CharField(verbose_name=_(u'post meta title'),
                                    help_text=_(u'used in title tag and social sharing'),
                                    max_length=255,
                                    blank=True, default=''),
        post_text=RichTextUploadingField(_(u'text'), default='', blank=True),
        meta={'unique_together': (('language_code', 'slug'),)}
    )
    content = PlaceholderField('post_content', related_name='advisor_post_content')

    objects = GenericDateTaggedManager()
    tags = TaggableManager(blank=True, related_name='advisor_tags')

    _metadata = {
        'title': 'get_title',
        'description': 'get_description',
        'og_description': 'get_description',
        'twitter_description': 'get_description',
        'gplus_description': 'get_description',
        'keywords': 'get_keywords',
        'locale': None,
        'image': 'get_image_full_url',
        'object_type': get_setting('TYPE'),
        'og_type': get_setting('FB_TYPE'),
        'og_app_id': get_setting('FB_APPID'),
        'og_profile_id': get_setting('FB_PROFILE_ID'),
        'og_publisher': get_setting('FB_PUBLISHER'),
        'og_author_url': get_setting('FB_AUTHOR_URL'),
        'twitter_type': get_setting('TWITTER_TYPE'),
        'twitter_site': get_setting('TWITTER_SITE'),
        'twitter_author': get_setting('TWITTER_AUTHOR'),
        'gplus_type': get_setting('GPLUS_TYPE'),
        'gplus_author': get_setting('GPLUS_AUTHOR'),
        'published_time': 'date_published',
        'modified_time': 'date_modified',
        'expiration_time': 'date_published_end',
        'tag': 'get_tags',
        'url': 'get_absolute_url',
    }

    class Meta:
        verbose_name = _('advisor article')
        verbose_name_plural = _('advisor articles')
        ordering = ('-date_published', '-date_created')
        get_latest_by = 'date_published'

    def __str__(self):
        return self.safe_translation_getter('title')

    def get_absolute_url(self):
        def get_slug(ctg):
            return ctg.safe_translation_getter(
                'slug', language_code=get_language(),
                any_language=True)
        catgrs_slug = [get_slug(self)]
        catgr = self.categories.all().prefetch_related('parent').first()
        """@type: AdvisorCategory"""
        catgrs_slug.append(get_slug(catgr))
        while catgr.parent is not None:
            catgr = catgr.parent
            catgrs_slug.append(get_slug(catgr))
        catgrs_slug.reverse()
        return reverse('advisor:post-detail', kwargs={'path': '/'.join(catgrs_slug)})

    def save(self, *args, **kwargs):
        super(Post, self).save(*args, **kwargs)
        main_lang = self.get_current_language()
        for lang in self.get_available_languages():
            self.set_current_language(lang)
            if not self.slug and self.title:
                self.slug = slugify(self.title)
        self.set_current_language(main_lang)
        self.save_translations()

    def get_title(self):
        title = self.safe_translation_getter('meta_title', any_language=True)
        if not title:
            title = self.safe_translation_getter('title', any_language=True)
        return title.strip()

    def get_keywords(self):
        return self.safe_translation_getter('meta_keywords').strip().split(',')

    def get_description(self):
        description = self.safe_translation_getter('meta_description', any_language=True)
        if not description:
            description = self.safe_translation_getter('abstract', any_language=True)
        return escape(strip_tags(description)).strip()

    def get_image_full_url(self):
        if self.main_image:
            return self.make_full_url(self.main_image.url)
        return ''

    def get_tags(self):

apps/advisor/forms.py
# coding=utf-8

from django import forms
from taggit_autosuggest.widgets import TagAutoSuggest


class LatestEntriesForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(LatestEntriesForm, self).__init__(*args, **kwargs)
        self.fields['tags'].widget = TagAutoSuggest('taggit.Tag')

    class Media:
        css = {
            'all': ('css/advisor_admin.css',)
        }


class SearchForm(forms.Form):
    query = forms.CharField(max_length=100, min_length=1)

templates/advisor/base.html
{% extends 'base.html' %}

{% load menu_tags i18n cms_tags staticfiles sekizai_tags %}

{% block meta %}{%  if meta %}
    {% include "meta_mixin/meta.html" %}
{% endif %}{% endblock %}

{% block base_header %}

    {% addtoblock 'css' %}
        <link rel="stylesheet" href="{% static 'css/advisor.css' %}" media="screen"/>
    {% endaddtoblock %}

    <h1>{% trans "Adviser" %}</h1>
    <div class="lead">{% placeholder 'advisor_lead' or %}<p>{% blocktrans trimmed %}
        With a bereavement many organisationally and legally necessary steps are connected. Of the
        Funeral workers want to help you with important information in preparing the burial and
        Find contact persons and literature in the situation of mourning.
    {% endblocktrans %}</p>{% endplaceholder %}</div>

{% endblock %}

{% block content %}
<div class="app app-advisor">
    <nav class="left-menu"><ul>
        {% show_menu 1 2 0 1 "menu.html" %}
{% comment %}
            <li><a href="#">Bestattung</a></li>
            <li><a href="#">Bestattungsarten</a></li>
            <li><a href="#">Bestattungskosten</a></li>
            <li><a href="#">Erbe</a></li>
            <li><a href="#">Grab</a></li>
{% endcomment %}
    </ul></nav>
    {% block content_blog %}{% endblock %}
</div>
{% endblock content %}

templates/advisor/post_archive.html
{% extends "advisor/post_list.html" %}

templates/advisor/post_detail.html
{% extends "advisor/base.html" %}
{% load i18n thumbnail cms_tags sekizai_tags staticfiles %}

{% block meta_description %}{{ post.meta_description }}{% endblock meta_description %}
{% block meta_keywords %}{{ post.meta_keywords }}{% endblock meta_keywords %}
{% block canonical_url %}<link rel="canonical" href="{{ SITE.domain }}{{ view.get_view_url }}"/>{% endblock canonical_url %}
{% block title %}{{ post.get_title }}{% endblock %}

{% block content_blog %}
    <article id="post-{{ post.slug }}" class="post-item post-detail">
        <header>
            {% if post.main_image_id %}
                {% thumbnail post.main_image post.full_image_options.size crop=post.full_image_options.crop upscale=post.full_image_options.upscale subject_location=post.main_image.subject_location as thumb %}
                <img src="{{ thumb.url }}" alt="{{ post.main_image.default_alt_text }}" width="{{ thumb.width }}" height="{{ thumb.height }}"/>
            {% endif %}
            <h1>{% render_model post "title" %}</h1>
        </header>
        <div class="blog-content">
            {% if use_placeholder %}{% render_placeholder post.content %}
            {% else %}{% render_model post "post_text" "post_text" %}
            {% endif %}
        </div>
    </article>
    {% addtoblock 'js' %}<script src="{% static 'js/zoom.js' %}"></script>{% endaddtoblock %}
{% endblock content_blog %}

templates/advisor/post_list.html
{% extends "advisor/base.html" %}

{% load i18n thumbnail cms_tags staticfiles %}


{% block canonical_url %}<link rel="canonical" href="{{ SITE.domain }}{{ view.get_view_url }}"/>{% endblock canonical_url %}


{% block content_blog %}
    <section class="blog-list">{% spaceless %}
        {% for post in post_list %}
            {% include "advisor/includes/item.html" with post=post image="true" %}
        {% empty %}
        <p class="blog-empty">{% trans "No article found." %}</p>
        {% endfor %}
        {% if author or archive_date or tagged_entries %}
        <p class="blog-back"><a href="{% url 'advisor:posts-latest' %}">{% trans "Back" %}</a></p>
        {% endif %}
        {% if is_paginated %}
        <nav class="{% firstof css_grid instance.css_grid %} pagination">
            {% if page_obj.has_previous %}
                <a href="?{{ view.page_kwarg }}={{ page_obj.previous_page_number }}">&laquo; {% trans "previous" %}</a>
            {% endif %}
            <span class="current">
                {% trans "Page" %} {{ page_obj.number }} {% trans "of" %} {{ paginator.num_pages }}
            </span>
            {% if page_obj.has_next %}
                <a href="?{{ view.page_kwarg }}={{ page_obj.next_page_number }}">{% trans "next" %} &raquo;</a>
            {% endif %}
        </nav>
        {% endif %}
    {% endspaceless %}</section>
{% endblock %}

templates/advisor/search_result.html
{% extends "advisor/base.html" %}

{% load i18n thumbnail cms_tags staticfiles %}



{% block canonical_url %}<link rel="canonical" href="{{ SITE.domain }}{{ view.get_view_url }}"/>{% endblock canonical_url %}

{% block content_blog %}
    <section class="blog-list">{% spaceless %}
        {% block blog_title %}
            <header>{% placeholder 'header_image' or %}
                <img src="{% static 'img/advisor_index.jpg' %}" width="690" height="215"/>
            {% endplaceholder %}</header>
        {% endblock %}
        <div class="search-query">{% trans 'Search results for' %} <q>{{ view.form.cleaned_data.query }}</q>:</div>{#  Suchergebnisse fur #}
        {% for post in post_list %}
            {% include "advisor/includes/item.html" with post=post image="false" TRUNCWORDS_COUNT=TRUNCWORDS_COUNT num=forloop.counter %}
        {% empty %}
        <p class="blog-empty">{% trans "No article found." %}</p>
        {% endfor %}
        {% if author or archive_date or tagged_entries %}
        <p class="blog-back"><a href="{% url 'advisor:posts-latest' %}">{% trans "Back" %}</a></p>
        {% endif %}
        {% if is_paginated %}
        <nav class="{% firstof css_grid instance.css_grid %} pagination">
            {% if page_obj.has_previous %}
                <a href="?{{ view.page_kwarg }}={{ page_obj.previous_page_number }}">&laquo; {% trans "previous" %}</a>
            {% endif %}
            <span class="current">
                {% trans "Page" %} {{ page_obj.number }} {% trans "of" %} {{ paginator.num_pages }}
            </span>
            {% if page_obj.has_next %}
                <a href="?{{ view.page_kwarg }}={{ page_obj.next_page_number }}">{% trans "next" %} &raquo;</a>
            {% endif %}
        </nav>
        {% endif %}
    {% endspaceless %}</section>
{% endblock %}

templates/advisor/sub_topics_menu.html
{% spaceless %}

    {% load i18n cache %}

    {% for child in children %}
        <li><a href="{{ child.get_absolute_url }}">{{ child.get_menu_title }}</a></li>
        {% if forloop.counter|divisibleby:'5' %}</ul><ul>{% endif %}
    {% endfor %}

{% endspaceless %}