apps/advisor/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import feeds as fd
from . import views as v

urlpatterns = [
    url(r'^$', v.PostListView.as_view(), name='posts-latest'),
    url(r'^feed/$', fd.LatestEntriesFeed(), name='posts-latest-feed'),
    url(r'^(?P<year>\d{4})/$', v.PostArchiveView.as_view(), name='posts-archive'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', v.PostArchiveView.as_view(), name='posts-archive'),
    url(r'^author/(?P<username>[\w\.@+-]+)/$', v.AuthorEntriesView.as_view(), name='posts-author'),
    url(r'^category/(?P<category>[\w\.@+-]+)/$', v.CategoryEntriesView.as_view(), name='posts-category'),
    url(r'^tag/(?P<tag>[-\w]+)/$', v.TaggedListView.as_view(), name='posts-tagged'),
    url(r'^tag/(?P<tag>[-\w]+)/feed/$', fd.TagFeed(), name='posts-tagged-feed'),
    url(r'^search$', v.SearchListView.as_view(), name='posts-search'),
    url(r'^(?P<path>.+)$', v.PostDetailView.as_view(), name='post-detail'),
]

apps/catalog/urls.py
# coding=utf-8
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt
from . import views as v


urlpatterns = [
    url(r'^search/contact$', v.SaveSimpleUserContactView.as_view(), name='simple_contact'),
    url(r'^search$', v.SearchByFormView.as_view(), name='search'),
    url(r'^bestatter/(?P<char>\w)$', v.SearchByCharView.as_view(), name='search_char'),
    url(r'^xhr/(?P<action>\w+)$', csrf_exempt(v.XhrView.as_view()), name='xhr'),
    url(r'^(?P<slug>[\w\-]+)-(?P<uid>[0-9a-f]{32})/contact$', v.FirmContactView.as_view(), name='firm_contact'),
    url(r'^(?P<slug>[\w\-]+)-(?P<uid>[0-9a-f]{32})$', v.DetailView.as_view(), name='detail'),
    url(r'^$', v.IndexView.as_view(), name='index'),
]

funeral_finder_cms/urls.py
# coding=utf-8
from __future__ import print_function
from cms.sitemaps import CMSSitemap
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib.admin import site as admin_site
from django.contrib.auth import urls as auth_urls
from django.contrib.auth import logout
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.views.static import serve
from django.views.decorators.csrf import csrf_exempt
from .views import XhrView, account_activate
from catalog.views import ProfileFirmsView, FirmEditView
# admin.autodiscover()


def dummy(r):
    pass


# urlpatterns = i18n_patterns(
urlpatterns = [
    url(r'^admin/', include(admin_site.urls)),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^xhr/(?P<action>\w+)$', csrf_exempt(XhrView.as_view()), name='xhr'),
    url(r'^catalog/', include('catalog.urls', namespace='catalog', app_name='catalog')),
    # url(r'^auth/logout-when-redirect'),
    url(r'^auth/', include(auth_urls, namespace='auth')),
    url(r'^accounts/profile-firms$', ProfileFirmsView.as_view(), name='profile_firms'),
    url(r'^accounts/profile-firms/(?P<pk>\d+)$', FirmEditView.as_view(), name='firm_edit'),
    url(r'^accounts/registration/(?P<who>\w+)', dummy, name='registration'),
    url(r'^accounts/activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})$',
        account_activate, name='account_activate'),
    # url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    # url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
# )

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += [
        url(r'^media(?P<path>.*)$', serve,
            kwargs={'document_root': settings.MEDIA_ROOT,
                    'show_indexes': True}),
    ] + staticfiles_urlpatterns()
    try:
        import debug_toolbar
    except ImportError:
        pass
    else:
        urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]

urlpatterns += [
    url(r'^(?P<path>.+(\.ico|\.png|\.gif|\.jpg|\.jpeg|\.txt))$', serve,
        kwargs={'document_root': settings.PUB_ROOT}, name='public'),
    url(r'^', include('cms.urls')),
]

apps/catalog/models/price.py
# coding=utf-8
import django.db.models as d_m
from django.utils.translation import ugettext_lazy as _
from .company import Company


class Price(d_m.Model):
    company = d_m.ForeignKey(
        Company, verbose_name=_(u'company'), related_name='price_list',
        editable=False, null=True)
    active = d_m.BooleanField(_(u'is active?'), default=True)
    title = d_m.CharField(_(u'service type'), max_length=100)
    summa = d_m.DecimalField(_(u'price from'), max_digits=12, decimal_places=2)

    class Meta:
        verbose_name = _(u'Price')
        verbose_name_plural = _(u'Prices')

apps/catalog/forms.py
# coding=utf-8
import django.forms as d_f
from django.forms.models import modelformset_factory
from django.utils.translation import ugettext_lazy as _

from djangocms_text_ckeditor.widgets import TextEditorWidget

from . import models as m


class SearchForm(d_f.Form):
    # SERVICE_CHOICES = (
    #     (0, _(u'Show all')),
    #     (1, _(u'Funeral services')),
    #     (2, _(u'Funeral assistance and accompaniment')),
    #     (3, _(u'Funeral music')),  # Trauermusik
    #     (4, _(u'Sadness and grave speakers')),
    #     (5, _(u'Carpenters and Joiners')),
    #     (6, _(u'Cemetery gardener')),
    #     (7, _(u'Grave decorations and funeral flowers')),
    # )
    # # service = d_f.ChoiceField(choices=SERVICE_CHOICES, label=_(u'Service'), initial=1)
    query = d_f.CharField(max_length=100, min_length=1, label=u'Bestatter finden', label_suffix=u'...',
                          help_text=u'Bitte Ort oder Postleitzahl eingeben')


class ProfileForm(d_f.ModelForm):
    class Meta:
        model = m.Company
        fields = (
            'logo', 'title', 'street_house', 'postal_code',
            'city', 'phone', 'mail', 'website', 'description',
        )
        labels = {
            'logo': u'Logo upload'
        }
        # widgets = {
        #     'description': TextEditorWidget()
        # }


class PriceForm(d_f.ModelForm):
    class Meta:
        model = m.Price
        fields = ('id', 'active', 'title', 'summa', )
        labels = {
            'active': u' '
        }

    def __init__(self, **kwargs):
        kwargs.update(label_suffix='')
        super(PriceForm, self).__init__(**kwargs)


PriceFormSet = modelformset_factory(m.Price, form=PriceForm, min_num=2, max_num=2, extra=2)


class _ContactForm(d_f.Form):
    name = d_f.CharField(max_length=200, min_length=1, label=u'Name und Vorname *')
    mail = d_f.EmailField(label=u'E-mail adresse *')


class SimpleContactForm(_ContactForm):
    is_agree = d_f.BooleanField(label=u'* Ich bin mit der Weitergabe meiner Email-Adresse an bei „Bestattungshilfe“'
                                      u' registrierte Firmen einverstanden.')
    firm_id = d_f.IntegerField(widget=d_f.HiddenInput)
    # last_query = d_f.CharField(widget=d_f.HiddenInput)

    def clean_is_agree(self):
        _val = self.cleaned_data['is_agree']
        if not _val:
            raise d_f.ValidationError(u'You don\'t agree with rules!')
        return _val

    def clean(self):
        cleaned_data = super(SimpleContactForm, self).clean()
        _id = cleaned_data.get('firm_id', None)
        if not _id:
            raise d_f.ValidationError(u'Firm id is empty!')
        elif not m.Company.companies.filter(pk=_id).exists():
            raise d_f.ValidationError(u'Firm does not exists!')


class FullContactForm(_ContactForm):
    address = d_f.CharField(max_length=200, label=u'Anschrift *')
    phone = d_f.CharField(max_length=20, label=u'Telefon', required=False,
                          widget=d_f.TextInput({'type': 'tel'}))
    message = d_f.CharField(max_length=2000, label=u'Nachricht an den Anbieter *', widget=d_f.Textarea)

apps/catalog/views.py
# coding=utf-8
import re
import urllib

import django.http as d_h
import django.views.generic as d_v
from django.utils.translation import ugettext as _
# import django.core.mail as d_mail
# import django.core.signing as d_sign
from django.core.paginator import InvalidPage
import django.shortcuts as d_sc
# from django.conf import settings as d_st
# from django.contrib.auth import authenticate
from django.views.generic.edit import BaseUpdateView, ModelFormMixin
from funeral_finder_cms.paginator import CustomPaginator
from . import models as m
from . import forms as f
from funeral_finder_cms.views import BaseXhrView
from django.http.request import QueryDict
# import django.contrib.auth as d_a
# import django.core.urlresolvers as d_urls
from . import tasks as tsk
import logging
log = logging.getLogger('funeral_finder_cms')


not_dig_patt = re.compile(r'\D+')


def format_phone(num):
    num = not_dig_patt.sub(u'', num)
    if len(num) == 11:
        disp = num[0:3] + ' ' + num[3:7] + ' ' + num[7:]
    else:
        disp = num
    return num, disp


class XhrView(BaseXhrView):

    def query_contact(self, params=None):
        ret_data = {
            'status': u'error',
            'errors': None,
            'next': ''}
        form = f.SimpleContactForm(data=params)
        name = None
        mail = None
        if form.is_valid():
            cd = form.cleaned_data
            name = urllib.unquote_plus(form.cleaned_data['name'])
            mail = urllib.unquote_plus(form.cleaned_data['mail'])
            sess = self.request.session
            """@type: django.contrib.sessions.base.SessionBase"""
            sess['contact'] = {'name': name, 'mail': mail}
            firm = m.Company.companies.get(pk=cd['firm_id'])
            """@type: Company"""
            ret_data['status'] = u'ok'
            ret_data['next'] = firm.get_contact_url()
            sess['last_firm_id'] = firm.id
        else:
            ret_data['errors'] = form.errors
        resp = d_h.JsonResponse(ret_data)
        if name and mail:
            resp.set_signed_cookie('contact_name', name, httponly=True)
            resp.set_signed_cookie('contact_mail', mail, httponly=True)
        return resp

    def get_phone(self, params=None):
        # log.debug(u'PARAMS: %r' % params)
        ret_data = {'status': u'error', 'errors': None}
        if isinstance(params, QueryDict):
            firm = params.get('firm')
            """@type: unicode"""
            if firm.isdigit():
                company_id = int(firm)
                try:
                    company = m.Company.companies.get(pk=company_id)
                except m.Company.DoesNotExist:
                    ret_data.update(errors=[u'Company does not exist'])
                else:
                    # import random
                    # num_int = random.randint(1, 99)
                    # num = format(num_int, u'0=#2')
                    num, disp = format_phone(company.phone)
                    ret_data = {
                        'status': u'ok',
                        # 'phone': u'030123456%s' % num,
                        'phone': num,
                        # 'display': u'030 123456-%s' % num
                        'display': disp,
                    }
        else:
            ret_data.update(errors=[u'No params', ])
        return d_h.JsonResponse(ret_data)


class GetContactMixin(object):
    request = None
    """@type: django.http.request.HttpRequest"""
    mail = None
    name = None
    is_gave_contact = False

    def get_contact(self):
        contact = self.request.session.get('contact', None)
        if contact:
            self.name = contact['name']
            self.mail = contact['mail']
            self.is_gave_contact = True
        else:
            self.name = self.request.get_signed_cookie('contact_name', '')
            self.mail = self.request.get_signed_cookie('contact_mail', '')
            if self.name and self.mail:
                self.is_gave_contact = True
                self.request.session['contact'] = {
                    'name': self.name,
                    'mail': self.mail
                }


class IndexView(d_v.TemplateView, GetContactMixin):
    http_method_names = ('get', 'head', )
    template_name = 'catalog/index.html'

    def get_context_data(self, **kwargs):
        kwargs.update(form=f.SearchForm())
        return super(IndexView, self).get_context_data(**kwargs)

    def get(self, request, *args, **kwargs):
        """
        Http get method
        @param request: http request
        @type request: django.http.request.HttpRequest
        @return: http response
        @rtype: django.http.response.HttpResponse
        """
        self.get_contact()
        return super(IndexView, self).get(request, *args, **kwargs)


class GeneralSearchView(d_v.ListView, GetContactMixin):
    http_method_names = ('get', )
    template_name = 'catalog/search_details.html'
    list_template_name = 'catalog/.include/items_list.html'
    allow_empty = True
    paginate_by_kwarg = 'paginate_by'
    paginate_by_nums = (10, 20, 50, 100, )
    paginate_by = 10
    paginator_class = CustomPaginator
    context_object_name = 'firms'
    model = m.Company
    uri_query = None
    page_patt = re.compile(r'page=\d+')

    def get_paginate_by(self, queryset):
        """
        Get size of pagination
        @param queryset: queryset object
        @type queryset: django.db.models.QuerySet
        @return: number
        @rtype: int
        """
        req = self.request
        """@type: django.http.request.HttpRequest"""
        sess = getattr(req, 'session')
        """@type: django.contrib.sessions.backends.base.SessionBase"""
        paginate_by_kwarg = self.paginate_by_kwarg
        paginate_by = self.kwargs.get(paginate_by_kwarg) or req.GET.get(paginate_by_kwarg)
        if paginate_by is None:
            paginate_by = sess.get(paginate_by_kwarg, self.paginate_by)
        else:
            sess[paginate_by_kwarg] = paginate_by
        self.paginate_by = paginate_by
        if queryset.query.high_mark is None:
            return paginate_by
        return None

    def paginate_queryset(self, queryset, page_size):
        """
        Paginate the queryset, if needed.
        """
        paginator = self.get_paginator(
            queryset, page_size, orphans=self.get_paginate_orphans(),
            allow_empty_first_page=self.get_allow_empty())
        page_kwarg = self.page_kwarg
        page = self.kwargs.get(page_kwarg) or self.request.GET.get(page_kwarg) or 1
        try:
            page_number = int(page)
        except ValueError:
            if page == 'last':
                page_number = paginator.num_pages
            else:
                raise d_h.Http404(_("Page is not 'last', nor can it be converted to an int."))
        page = paginator.page(page_number)
        return paginator, page, page.object_list, page.has_other_pages()

    def get_queryset(self):
        qs = super(GeneralSearchView, self).get_queryset()
        """@type: CompaniesQuerySet"""
        # return qs.prefetch_related('price_list').with_mail()
        return qs.prefetch_related('price_list')

    def get(self, request, *args, **kwargs):
        """
        Http GET request hanler
        @param request: http request object
        @type request: django.http.request.HttpRequest
        @return: http response object
        @rtype: django.http.response.HttpResponse
        """
        self.get_contact()
        req_get = request.GET
        """@type: django.http.request.QueryDict"""
        if 'page' in req_get:
            get_params = req_get.copy()
            del get_params['count']
            del get_params['page']
            self.uri_query = get_params.urlencode()
        else:
            self.uri_query = req_get.urlencode()
        try:
            return super(GeneralSearchView, self).get(request, *args, **kwargs)
        except InvalidPage:
            return d_h.HttpResponseRedirect(
                self.page_patt.sub('page=1', request.get_full_path()))


class SearchByFormView(GeneralSearchView):
    srch_patt = re.compile(r'(\d{5})\W+(\w+)', re.U | re.I)
    form = None
    list_mode = 'form_search'

    def get_context_data(self, **kwargs):
        kwargs.update(
            form=self.form,
            contact_form=f.SimpleContactForm())
        return super(SearchByFormView, self).get_context_data(**kwargs)

    def get_queryset(self):
        str_query = self.form.cleaned_data['query']
        """@type: unicode"""
        srch_res = self.srch_patt.match(str_query)
        qs = super(SearchByFormView, self).get_queryset()
        if srch_res:
            qs = qs.by_code(srch_res.group(1), srch_res.group(2))
        elif str_query.isdecimal():
            qs = qs.by_code(str_query)
        else:
            qs = qs.by_place(str_query)
        if qs is not None:
            return qs
        return m.Company.companies.none()

    def get(self, request, *args, **kwargs):
        """
        Http GET request hanler
        @param request: http request object
        @type request: django.http.request.HttpRequest
        @return: http response object
        @rtype: django.http.response.HttpResponse
        """
        self.form = f.SearchForm(request.GET)
        if not self.form.is_valid():
            return d_sc.redirect('pages-root')
        request.session['search_url'] = request.get_full_path()
        request.session['last_query'] = self.form.cleaned_data['query']
        return super(SearchByFormView, self).get(request, *args, **kwargs)


class SearchByCharView(GeneralSearchView):
    list_mode = 'char_search'

    def get_context_data(self, **kwargs):
        kwargs.update(
            char=self.kwargs['char'],
            contact_form=f.SimpleContactForm())
        return super(SearchByCharView, self).get_context_data(**kwargs)

    def get_queryset(self):
        qs = super(SearchByCharView, self).get_queryset()

templates/catalog/.include/contact_info.html
<figure class="col f">
    {% if view.template_name_suffix == '_detail' %}
        <a href="{{ company.google_de_map_url }}">{% include 'catalog/.include/map_img.html' %}</a>
    {% else %}
        {% include 'catalog/.include/map_img.html' %}
    {% endif %}
    <figcaption>
{#        <h3>{{ firm.title }}</h3>#}
        {% if company.street_house %}
            <address>{{ company.street_house }}, {{ company.postal_code }}&nbsp;{{ company.city }}</address>
        {% endif %}
        <address class="add-info">
            {% if company.website %}<div class="website">{{ company.website|cut:"http://" }}</div>{% endif %}
            {% if company.mail %}<div class="mail">{{ company.mail }}</div>{% endif %}
        </address>
        {% if company.phone %}
            <address class="phone">
            {% if user == company.user %}{{ company.phone }}
            {% else %}
            <div class="get-phone">
                <span id="company-{{ company.id }}-phone">{{ company.phone|truncatechars:7 }}</span><br/>
                <a class="req" href="{% url 'catalog:detail' slug=company.slug uid=company.uid %}" data-action="get_phone" data-firm="{{ company.id }}">Telefonnummer anzeigen</a>
            </div>
            {% endif %}
            </address>
        {% endif %}
    </figcaption>


</figure>

templates/catalog/.include/footer_links.html
            <ul class="footer-links">{% url 'search' as srch_url %}
                <li><ul>
                    <li><a href="{{ srch_url }}?query=Berlin">Bestattung in Berlin</a></li>
                    <li><a href="{{ srch_url }}?query=Hamburg">Bestattung in Hamburg</a></li>
                    <li><a href="{{ srch_url }}?query=M%C3%BCnchen">Bestattung in München</a></li>
                </ul></li>
                <li><ul>
                    <li><a href="{{ srch_url }}?query=K%C3%B6ln">Bestattung in Köln</a></li>
                    <li><a href="{{ srch_url }}?query=Frankfurt%20am%20Main">Bestattung in Frankfurt</a></li>
                    <li><a href="{{ srch_url }}?query=Stuttgart">Bestattung in Stuttgart</a></li>
                </ul></li>
                <li><ul>
                    <li><a href="{{ srch_url }}?query=D%C3%BCsseldorf">Bestattung in Düsseldorf</a></li>
                    <li><a href="{{ srch_url }}?query=Dortmund">Bestattung in Dortmund</a></li>
                    <li><a href="{{ srch_url }}?query=Essen">Bestattung in Essen</a></li>
                </ul></li>
                <li><ul>
                    <li><a class="mark" href="{% url 'about' %}">AGB & Datenschutz</a></li>
                    <li><a href="{% url 'imprint' %}">Impressum</a></li>
                    <li><a href="{% url 'contacts' %}">Kontakt & Service</a></li>
                </ul></li>
            </ul>

templates/catalog/.include/input_block.html
{% load widget_tweaks form_utils %}
{{ field.errors }}
{% if field|widget_type in 'checkboxinput,radioinput' %}
    <div class="input-block {{ field|widget_type }}">
        {% render_field field %}
        {% render_label field %}
    </div>
{% else %}
    <div id="{{ field.html_name }}_block" class="input-block {{ field|widget_type }}">
        {% render_label field class=label_class %}
        {% if field|widget_type == 'textarea' %}
            {% render_field field placeholder=field.label class+='inp-text' cols='' rows='' %}
        {% elif field|widget_type == 'select' %}
            {% render_field field class+='inp-sel placeholder' %}
        {% else %}
            {% render_field field placeholder=field.label class+='inp-str' %}
        {% endif %}
    </div>
{% endif %}

templates/catalog/.include/items_list.html
{% load staticfiles text_utils %}
{% for company in firms %}{# @type: Company #}
    <article class="search-item" id="company-{{ company.id }}">
        <header>
            <h1><a href="#company-{{ company.id }}" class="show-info">{{ company.title|split_title|safe }}</a></h1>
            <a href="#company-{{ company.id }}" class="distance show-info"><span>
                {% if company.distance %}<b>{{ company.distance }}&nbsp;km</b> entfernt
                {% else %}{{ company.city }}{% endif %}
            </span></a><br/>
            {% if company.mail %}<a class="btn contact" href="{{ company.get_contact_url }}">Kontakt aufnehmen</a>{% endif %}
{% comment %}
            {% if not view.is_gave_contact %}
                <button class="btn contact" data-modal-id="contact" data-firm-id="{{ company.id }}">Kontakt aufnehmen</button>
            {% else %}
                <a class="btn contact" href="{{ company.get_contact_url }}">Kontakt aufnehmen</a>
            {% endif %}
{% endcomment %}
        </header>
        <hr/>
        <div class="roll">
            <div class="info">
                {% include 'catalog/.include/contact_info.html' %}
                <div class="col s">
                    {% if company.description %}
                        {% with trunc_description=company.description|truncatewords_html:50 %}
                            {{ trunc_description|safe }}
                            {% if company.description|length > trunc_description|length %}
                                <div class="detail-link">
                                    <a href="{{ company.get_absolute_url }}">Weiter zur Detailseite</a>
                                </div>
                            {% endif %}
                        {% endwith %}
                    {% else %}
                        <p>Keine Beschreibung vorhanden</p>
                    {% endif %}
                </div>
                <div class="col t">
                    {% include 'catalog/.include/logo.html' with logo=company.logo title=company.title %}
                    {% include 'catalog/.include/price_list.html' with price_list=company.price_list.all only %}
                </div>
            </div>
        </div>
        <footer>
            <a href="#company-{{ company.id }}" class="more show-info">Mehr Informationen</a>
        </footer>
    </article>
{% endfor %}

templates/catalog/.include/logo.html
{% spaceless %}{% load staticfiles %}
<figure class="org-logo">
    {% if logo %}
        <img src="{{ logo.url }}" title="{{ title }}"/>
    {% else %}
        <img src="{% static 'img/no-logo.png' %}" title="No logotip for «{{ title }}»"/>
    {% endif %}
</figure>
{% endspaceless %}

templates/catalog/.include/manager_items_list.html
{% for firm in firms %}
    <article class="search-item" id="company-{{ firm.id }}">
        <header>
            <h1><a href="{{ firm.get_absolute_url }}" class="show-info">{{ firm.title }}</a></h1>
            <a href="{{ firm.google_de_map_url }}" class="distance show-info"><span>{{ firm.city }}</span></a>
            <a class="btn contact" href="{{ firm.get_edit_url }}">Editieren</a>
        </header>
        <hr/>
    </article>
{% endfor %}

templates/catalog/.include/map_img.html
<img src="{{ company.google_static_map_url }}" width="220" height="166" title="{{ company.full_addr }}"/>

templates/catalog/.include/pagination.html
<div class="pagination">
    <div class="count">{{ p_by }} Einträge pro Seite</div>
    <nav class="pages">{% spaceless %}
        <div class="icons l">
            {% if curr_num != 1 %}
                {% include 'catalog/.include/pagination_url.html' with query=view.uri_query num=1 cnt=p_by a_class='first icon' a_text='first' %}
            {% endif %}
            {% if page_obj.has_previous %}
                {% include 'catalog/.include/pagination_url.html' with query=view.uri_query num=page_obj.previous_page_number cnt=p_by a_class='prev icon' a_text='previous' %}
            {% endif %}
        </div>
        <ul>{% for p in paginator.page_range %}
            <li>{% if p != curr_num %}
                {% include 'catalog/.include/pagination_url.html' with query=view.uri_query num=p cnt=p_by a_class='' a_text=p %}
            {% else %}
                {% include 'catalog/.include/pagination_url.html' with query=view.uri_query num=p cnt=p_by a_class='curr' a_text=p %}
            {% endif %}</li>
        {% endfor %}</ul>
        <div class="icons r">
            {% if page_obj.has_next %}
                {% include 'catalog/.include/pagination_url.html' with query=view.uri_query num=page_obj.next_page_number cnt=p_by a_class='next icon' a_text='next' %}
            {% endif %}
            {% if curr_num != paginator.num_pages %}
                {% include 'catalog/.include/pagination_url.html' with query=view.uri_query num=paginator.num_pages cnt=p_by a_class='last icon' a_text='last' %}
            {% endif %}
        </div>
    {% endspaceless %}</nav>
</div>

templates/catalog/.include/pagination_url.html
<a {% if curr_num != num %}href="{% if query %}?{{ query }}&page={{ num }}&count={{ cnt }}{% else %}?page={{ num }}&count={{ cnt }}{% endif %}" {% endif %}class="{{ a_class }}">{{ a_text }}</a>

templates/catalog/.include/price_list.html
{% if price_list|length > 0 %}
    <div class="price">
        <h2>Preise</h2>
        <ul>{% for item in price_list %}
            <li>{{ item.title }}: ab&nbsp;{{ item.summa }} €</li>
        {% endfor %}</ul>
    </div>
{% endif %}

templates/catalog/.include/search_form.html
        <form action="{% url 'catalog:search' %}" method="get" class="input-group" name="search">{% spaceless %}
            {% load widget_tweaks form_utils %}
            {% render_label form.query class='sr-only' %}
            {% render_field form.query class+='inp-str' placeholder=form.query.label autofocus='' %}
            <span class="input-group-btn">
                <button type="submit" class="btn"><span>Suchen</span></button>
            </span>
        {% endspaceless %}</form>